locale: en
title: Alexander D Huang's Homepage
description: Enjoy writting
url: https://alxddh.github.io
logo: /logo.png
date_format: "%b %d %Y"
read_time: false
words_per_minute: 200
mathjax: true
permalink: /:year/:month/:day/:title.html

exclude:
  - scripts/

author:
  name: Alexander D Huang
  picture: /logo.png
  links: 
    - title: Twitter
      url: https://twitter.com/alxddh
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/alxddh
      icon: fab fa-github-square
    - title: Instagram
      url: https://www.instagram.com/alexanderdhuang/
      icon: fab fa-instagram

defaults:
  - scope:
      path: ""      
      type: "posts"
    values:
      layout: "post"
      share: true

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

disqus:
  shortname: alxddh

google_analytics: UA-149346707-1

footer_links:
  - title: Twitter
    url: https://twitter.com/alxddh
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/alxddh
    icon: fab fa-github-square
  - title: StackOverflow
    url: https://stackoverflow.com/users/12177595/alxddh
    icon: fab fa-stack-overflow
  - title: Instagram
    url: https://www.instagram.com/alexanderdhuang/
    icon: fab fa-instagram
  - title: Feed
    url: feed.xml
    icon: fas fa-rss-square

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

remote_theme: alxddh/so-simple-theme@alxddh

paginate: 10  # amount of posts to show per page
paginate_path: /page:num/
